[supervisord]
nodaemon=true
logfile=/home/dev/.cache/supervisor/supervisord.log
pidfile=/home/dev/.cache/supervisor/supervisord.pid
childlogdir=/home/dev/.cache/supervisor

[unix_http_server]
file=/home/dev/.cache/supervisor/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///home/dev/.cache/supervisor/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[include]
files = /home/dev/.config/supervisor/conf.d/*.conf

