#!/usr/bin/env bash
set -euo pipefail

read_secret_file() {
  local value_var="$1"
  local file_var="$2"
  local file_path="${!file_var:-}"

  if [ -n "$file_path" ]; then
    if [ ! -r "$file_path" ]; then
      echo "${file_var} points to an unreadable file: ${file_path}" >&2
      exit 1
    fi
    export "${value_var}=$(tr -d '\r\n' < "$file_path")"
  fi
}

bool_value() {
  case "${1:-}" in
    true|TRUE|1|yes|YES|on|ON) printf '%s' true ;;
    false|FALSE|0|no|NO|off|OFF) printf '%s' false ;;
    *) echo "invalid boolean value: ${1:-}" >&2; exit 1 ;;
  esac
}

if [ $# -gt 0 ]; then
  case "$1" in
    sh|bash|mcpproxy|node|npm|npx|python|python3|uv|uvx)
      exec "$@"
      ;;
  esac
fi

read_secret_file MCPPROXY_API_KEY MCPPROXY_API_KEY_FILE

if [ -z "${MCPPROXY_API_KEY:-}" ] && [ "${MCPPROXY_ALLOW_AUTOGENERATED_API_KEY:-false}" != "true" ]; then
  echo "MCPPROXY_API_KEY or MCPPROXY_API_KEY_FILE is required." >&2
  echo "Set MCPPROXY_ALLOW_AUTOGENERATED_API_KEY=true only for private first-run setup." >&2
  exit 1
fi

listen="${MCPPROXY_LISTEN:-0.0.0.0:8080}"
data_dir="${MCPPROXY_DATA_DIR:-/var/lib/mcpproxy}"
require_mcp_auth="$(bool_value "${MCPPROXY_REQUIRE_MCP_AUTH:-true}")"
enable_socket="$(bool_value "${MCPPROXY_ENABLE_SOCKET:-false}")"

args=(
  mcpproxy
  serve
  --listen "$listen"
  --data-dir "$data_dir"
  --require-mcp-auth="$require_mcp_auth"
  --enable-socket="$enable_socket"
)

if [ -n "${MCPPROXY_CONFIG:-}" ]; then
  args+=(--config "$MCPPROXY_CONFIG")
fi

if [ -n "${MCPPROXY_LOG_LEVEL:-}" ]; then
  args+=(--log-level "$MCPPROXY_LOG_LEVEL")
fi

if [ -n "${MCPPROXY_DISABLE_MANAGEMENT:-}" ]; then
  args+=(--disable-management="$(bool_value "$MCPPROXY_DISABLE_MANAGEMENT")")
fi

if [ -n "${MCPPROXY_READ_ONLY:-}" ]; then
  args+=(--read-only="$(bool_value "$MCPPROXY_READ_ONLY")")
fi

exec "${args[@]}" "$@"
